### ISSUE TITLE
how to update the transition values 

### ISSUE THREAD

**Issue by suhailwy** [indevizible/EasyTransition#2]
after presenting the view, how can we update the transition values on fly?

**Comment by indevizible** [comment]
Did you mean update values of EasyTransition object after presenting ?

**Comment by suhailwy** [comment]
yes, how can we update the height  (transition!.sizeMax) for the presented view controller.

**Comment by indevizible** [comment]
hmm I have no idea to do that, if you have any suggest please pr to my repo thanks.
